trigger:
  - "*"

pool:
  name: Default

variables:
  buildConfiguration: "Release"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "22.x"
    displayName: "Install Node.js and npm"

  - script: npm install
    workingDirectory: Tailspin.SpaceGame.Web
    displayName: "Install npm packages"

  - script: |
      node_modules\.bin\sass Tailspin.SpaceGame.Web\wwwroot:Tailspin.SpaceGame.Web\wwwroot
    displayName: "Compile Sass assets"

  - script: npm exec -- gulp
    workingDirectory: Tailspin.SpaceGame.Web
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: "Write build info"
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Build the project - Release"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration Release"
      projects: "**/*.csproj"